package:
  name: cyvlfeat
  version: {{ CONDACI_VERSION }}

requirements:
  host:
    - python
    - setuptools
    - numpy
    - cython
    - vlfeat

  run:
    - python
    - {{ pin_compatible('vlfeat', min_pin='x.x.x', max_pin='x.x.x') }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - pytest-cov

  imports:
    - cyvlfeat.sift.sift
    - cyvlfeat.sift.dsift
    - cyvlfeat.fisher.fisher
    - cyvlfeat.hog.hog
    - cyvlfeat.kmeans.kmeans
    - cyvlfeat.generic.generic

  commands:
    - pytest $SP_DIR/cyvlfeat -v --cov=cyvlfeat --cov-config .coveragerc

about:
  home: https://github.com/menpo/cyvlfeat/
  license: BSD
